name: .NET Backend Tests

on:
  push:
    branches: [ "main", "dev", "feature/**" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          nuget-${{ runner.os }}-

    - name: Restore dependencies
      run: dotnet restore RenovationApp.Tests/BackEnd.Tests/BackEnd.Tests.csproj

    - name: Build project
      run: dotnet build RenovationApp.Tests/BackEnd.Tests/BackEnd.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test RenovationApp.Tests/BackEnd.Tests/BackEnd.Tests.csproj --no-build --configuration Release --verbosity normal
